version: '3.8'
services:

  web:
    container_name: order
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - db
    ports:
     - 8080:8080
  db:
    container_name: database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: jejakin
