version: '3.8'
services:

  web:
    container_name: order
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - mongo
    ports:
     - 8080:8080
  mongo:
    container_name: db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: jejakin
