version: '3.8'
services:

  web:
    container_name: order
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: 'bitnami/mongodb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      - MONGODB_DATABASE=jejakin
    volumes:
     - db:/data/db

volumes:
  db: