

name: order test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: jejakin
        ports:
          - 3306:3306
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Write value to Properties-file
      uses: christian-draeger/write-properties@1.1.0
      with:
        path: './src/main/resources/application.properties'
        property: 'spring.data.mongodb.host'
        value: 'localhost'
    - name: build
      working-directory: ./order
      run: mvn clean package
    - name: run
      working-directory: ./order
      run: java -jar target/order-1.0.0.jar