name: Order CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-apps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker compose
      working-directory: ./order
      run: docker-compose up -d
  tests-apps:
    needs: run-apps
    runs-on: ubuntu-latest
    steps:
    - name: run test
      working-directory: ./order
      run: docker exec order mvn test