name: Order CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  defaults:
    working-directory: ./order
  run-apps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker compose
      run: docker-compose up -d
    - name: run test
      run: docker exec order mvn test