name: Order CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-apps:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: jejakin
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    defaults:
      run:
        working-directory: ./order
    steps:
    - uses: actions/checkout@v2
    - name: run docker compose
      run: docker-compose up -d
    - name: build
      run: docker exec order mvn clean package
