name: Order CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./order
jobs:
  run-apps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker compose
      run: docker-compose up -d
  tests-apps:
    needs: run-apps
    runs-on: ubuntu-latest
    steps:
    - name: run test
      run: docker exec order mvn test