name: Order CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./order
    steps:
    - uses: actions/checkout@v2
    - name: run docker compose
      run: docker-compose up -d
    - name: build
      run: docker exec order mvn clean package
